<?php

$options_launcher = array (
  'developer' => 'Zhareiv',
  'panel_address' => 'plugins',
  'name_script' => 'Video<b>it</b>',
  'script_version' => '1.1.5.0',
  'EdenPHP_name' => 'EdenPHP',
  'EdenPHP_version' => '0.0.0.7',
  'EdenPHP_data_url' => 'https://www.youtube.com/watch?v=S5UEoLeza-o',
  'plugins_dir' => 'plugins',
  'is_logged_data' => '571575887996622',
  'lang_admin' => 'english',
  'articles_active' => 'off',
  'comments_active' => 'on',
  'ad_blocker' => '',
  'google_analytics' => '',
  'smtp_or_mail' => 'smtp',
  'smtp_host' => '',
  'smtp_username' => '',
  'smtp_password' => '',
  'smtp_encryption' => '',
  'smtp_port' => '',
  'crypt_secret_key' => '',
  'crypt_password' => '',
  'ads_one' => '',
  'ads_two' => '',
  'ads_three' => '',
  'add_tag_ad_1' => '',
  'add_tag_ad_2' => '',
  'add_tag_ad_3' => '',
  'add_tag_ad_4' => '',
  'add_tag_ad_5' => '',
  'code' => 'A2',
  'limit_list_media' => '21',
  'update_youtube_key' => 1590468451,
  'email_admin_recovery' => 'game123727@gmail.com',
  'recovery_key' => 'keatembf6vkj73a9g2sk74khkr6uictecmkr836gh55tu',
  'security_login' => 0,
  'block_admin' => false,
  'news_data' => false,
  'total_access' => true,
  'dev_all' => 'off',
  'comments_active' => 'off',
); 

?>